---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &brew_image docker.io/homebrew/brew:4.5.11
  - &brew_base
    depends_on: []
    environment:
      HOMEBREW_COLOR: "true"
      HOMEBREW_DEVELOPER: "true"
      HOMEBREW_NO_AUTO_UPDATE: "True"
      HOMEBREW_NO_ENV_HINTS: "True"

steps:
  - name: test-git-sv
    image: *brew_image
    <<: *brew_base
    commands:
      - brew style ./Formula/git-sv.rb
      - brew install ./Formula/git-sv.rb
      - brew test ./Formula/git-sv.rb
